/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
    // New semantic names
    brand: "#53423C",
    "brand-hover": "#6c564f",
    header: "#53423C",
    "header-hover": "#6c564f",
    secondary: "#A68B7C",
    "secondary-hover": "#7a5d4c",
    success: "#065f46",
    "success-dark": "#34d399",
    warning: "#92400e",
    "warning-dark": "#facc15",
    danger: "#b91c1c",
    "danger-dark": "#f87171",
    background: "#E8E0DC",
    surface: "#ffffff",
    darkSurface: "#2d2d2d",
    text: "#1a1a1a",
    "text-dark": "#f5f5f5",
    "text-muted": "#6b4d43",
    "text-light": "#2b1e1a",
    "text-subtle": "#e0dcd9",
    "text-soft": "#f5f5f5",
    "text-placeholder": "#999",
    "form-bg": "#fef6f2",
    "form-bg-dark": "#1e1e1e",
    "input-light": "#fff",
    "input-dark": "#3b3b3b",
    "border-light": "#d6c7bf",
    "border-dark": "#666",

    // --- Temporary aliases (from Tailfinder) ---
    primary: "#53423C",
    "primary-hover": "#6c564f",
    reveal: "#53423C",
    "reveal-hover": "#8c705f",
    adoptedBadge: "#233511",
    "traffic-green": "#065f46",
    "traffic-green-dark": "#34d399",
    "traffic-yellow": "#92400e",
    "traffic-yellow-dark": "#facc15",
    "traffic-red": "#b91c1c",
    "traffic-red-dark": "#f87171",
    "text-base": "#1a1a1a",
    "text-base-dark": "#f5f5f5",
    "text-button-light": "#ffffff",
    card: "#ffffff",
    darkCard: "#2d2d2d",
  },
    },
  },
  plugins: [],
}
